# Generated by Django 3.2 on 2022-04-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220410_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='如果这里填写的价格为0,则表示当前课程被购买时，没有永久有效的期限', max_digits=6, verbose_name='课程原价'),
        ),
        migrations.CreateModel(
            name='CourseExpire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('expire_time', models.IntegerField(blank=True, help_text='有效期按天数计算', null=True, verbose_name='有效期')),
                ('expire_text', models.CharField(blank=True, max_length=64, null=True, verbose_name='有效期提示文本')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='课程价格')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_expire', to='course.course', verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程有效期选项',
                'verbose_name_plural': '课程有效期选项',
                'db_table': 'ly_course_expire',
            },
        ),
    ]
