# Generated by Django 3.2 on 2022-05-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220412_1918'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='dw_activity',
        ),
        migrations.AlterModelTable(
            name='course',
            table='dw_course',
        ),
        migrations.AlterModelTable(
            name='coursecategory',
            table='dw_course_category',
        ),
        migrations.AlterModelTable(
            name='coursechapter',
            table='dw_course_chapter',
        ),
        migrations.AlterModelTable(
            name='coursediscount',
            table='dw_course_discount',
        ),
        migrations.AlterModelTable(
            name='coursediscounttype',
            table='dw_course_discount_type',
        ),
        migrations.AlterModelTable(
            name='courseexpire',
            table='dw_course_expire',
        ),
        migrations.AlterModelTable(
            name='courselesson',
            table='dw_course_lesson',
        ),
        migrations.AlterModelTable(
            name='coursepricediscount',
            table='dw_course_price_dicount',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='dw_teacher',
        ),
    ]
