# Generated by Django 3.2 on 2022-05-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usercourse_buy_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='buy_number',
            new_name='trado_no',
        ),
    ]
