# Generated by Django 3.2 on 2022-05-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_buy_number_usercourse_trado_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credit',
            table='dw_credit',
        ),
        migrations.AlterModelTable(
            name='user',
            table='dw_user',
        ),
        migrations.AlterModelTable(
            name='usercourse',
            table='dw_user_course',
        ),
    ]
